package canvaseditor

import (
	"fmt"
	"sort"
	"strings"

	"github.com/SkylerGodfrey/magicmirror-agent/internal/canvas"
)

// emitPagesTf regenerates the full pages.tf from the canvas + pages
// map. Full regeneration is fine here because the editor owns this file
// end-to-end — there are no human-handwritten comments or attribute
// ordering preferences to preserve. The file's banner makes the
// "don't edit by hand" contract explicit.
//
// Output is sorted by page name for deterministic diffs across saves.
func emitPagesTf(c canvas.Canvas, pages map[string]canvas.Page) string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n")
	writeCanvas(&b, c)

	names := make([]string, 0, len(pages))
	for name := range pages {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		b.WriteString("\n")
		writePage(&b, name, pages[name])
	}
	return b.String()
}

const banner = `# Canvas v2 layout (HOM-102). Regenerated by magicmirror-agent's
# /canvas editor on each Save. Hand edits WILL be overwritten — make
# layout changes in the editor; if you need terraform-only fields the
# editor cannot express, declare them in modules.tf instead.
`

func writeCanvas(b *strings.Builder, c canvas.Canvas) {
	b.WriteString(`resource "magicmirror_canvas" "this" {
`)
	fmt.Fprintf(b, "  width         = %d\n", positiveOrDefault(c.Width, canvas.DefaultWidth))
	fmt.Fprintf(b, "  height        = %d\n", positiveOrDefault(c.Height, canvas.DefaultHeight))
	fmt.Fprintf(b, "  debug_borders = %t\n", c.DebugBorders)
	fmt.Fprintf(b, "  debug_labels  = %t\n", c.DebugLabels)
	fmt.Fprintf(b, "  default_page  = %q\n", defaultIfEmpty(c.DefaultPage, "home"))
	b.WriteString("}\n")
}

func writePage(b *strings.Builder, name string, page canvas.Page) {
	fmt.Fprintf(b, "resource \"magicmirror_page\" %q {\n", name)
	fmt.Fprintf(b, "  name = %q\n", name)
	if len(page.Slots) == 0 {
		b.WriteString("  slots = []\n")
		b.WriteString("}\n")
		return
	}
	b.WriteString("  slots = [\n")
	for _, slot := range page.Slots {
		writeSlot(b, slot)
	}
	b.WriteString("  ]\n")
	b.WriteString("}\n")
}

// One slot per line keeps the diff small when only an x/y changes — the
// human-eye `git diff` lights up on the right slot without dragging in
// neighbouring rectangles.
func writeSlot(b *strings.Builder, s canvas.Slot) {
	fmt.Fprintf(b,
		"    { module = %q, x = %d, y = %d, w = %d, h = %d, z_index = %d, hidden = %t },\n",
		s.Module, s.X, s.Y, s.W, s.H, s.ZIndex, s.Hidden,
	)
}

func positiveOrDefault(v, dflt int) int {
	if v <= 0 {
		return dflt
	}
	return v
}

func defaultIfEmpty(v, dflt string) string {
	if v == "" {
		return dflt
	}
	return v
}
