package canvaseditor

import (
	"strings"
	"testing"

	"github.com/SkylerGodfrey/magicmirror-agent/internal/canvas"
)

func TestEmitPagesTf_EmptyPages(t *testing.T) {
	out := emitPagesTf(canvas.Canvas{Width: 1080, Height: 1780, DefaultPage: "home"}, nil)
	if !strings.Contains(out, `resource "magicmirror_canvas" "this"`) {
		t.Errorf("expected canvas resource in output, got:\n%s", out)
	}
	if !strings.Contains(out, `width         = 1080`) {
		t.Errorf("expected width line, got:\n%s", out)
	}
	if !strings.Contains(out, `default_page  = "home"`) {
		t.Errorf("expected default_page line, got:\n%s", out)
	}
	if strings.Contains(out, "magicmirror_page") {
		t.Errorf("expected no page resources, got:\n%s", out)
	}
}

func TestEmitPagesTf_DeterministicOrder(t *testing.T) {
	c := canvas.Canvas{Width: 1080, Height: 1780, DefaultPage: "home"}
	pages := map[string]canvas.Page{
		"zulu": {Slots: []canvas.Slot{{Module: "clock", X: 0, Y: 0, W: 100, H: 100}}},
		"alpha": {Slots: []canvas.Slot{{Module: "weather", X: 0, Y: 0, W: 200, H: 200}}},
		"mike":  {Slots: []canvas.Slot{{Module: "calendar", X: 0, Y: 0, W: 300, H: 300}}},
	}

	out1 := emitPagesTf(c, pages)
	out2 := emitPagesTf(c, pages)
	if out1 != out2 {
		t.Fatal("emit not deterministic across calls")
	}

	idxAlpha := strings.Index(out1, `"alpha"`)
	idxMike := strings.Index(out1, `"mike"`)
	idxZulu := strings.Index(out1, `"zulu"`)
	if !(idxAlpha < idxMike && idxMike < idxZulu) {
		t.Errorf("expected alphabetical order alpha→mike→zulu, got positions %d, %d, %d",
			idxAlpha, idxMike, idxZulu)
	}
}

func TestEmitPagesTf_FullSlotShape(t *testing.T) {
	c := canvas.Canvas{Width: 1080, Height: 1780, DebugBorders: true, DefaultPage: "home"}
	page := canvas.Page{Slots: []canvas.Slot{
		{Module: "clock", X: 40, Y: 40, W: 500, H: 200, ZIndex: 1, Hidden: false},
		{Module: "MMM-Chores", X: 0, Y: 0, W: 1080, H: 1780, ZIndex: 5, Hidden: true},
	}}
	out := emitPagesTf(c, map[string]canvas.Page{"home": page})

	if !strings.Contains(out, `debug_borders = true`) {
		t.Errorf("debug_borders not propagated; got:\n%s", out)
	}
	if !strings.Contains(out, `module = "clock", x = 40, y = 40, w = 500, h = 200, z_index = 1, hidden = false`) {
		t.Errorf("clock slot line malformed; got:\n%s", out)
	}
	if !strings.Contains(out, `module = "MMM-Chores", x = 0, y = 0, w = 1080, h = 1780, z_index = 5, hidden = true`) {
		t.Errorf("MMM-Chores slot line malformed; got:\n%s", out)
	}
}

func TestEmitPagesTf_HasBanner(t *testing.T) {
	out := emitPagesTf(canvas.Canvas{Width: 1080, Height: 1780}, nil)
	if !strings.Contains(out, "Regenerated by magicmirror-agent") {
		t.Errorf("expected do-not-edit banner, got:\n%s", out)
	}
}
