package mascoteditor

import (
	"fmt"
	"strings"

	"github.com/SkylerGodfrey/magicmirror-agent/internal/mascot"
)

// emitMascotsTf regenerates the full mascots.tf from the canvas, sprite,
// and holiday lists. Full regeneration is fine because the editor owns
// this file end-to-end — there are no human-handwritten comments or
// attribute ordering preferences to preserve. The banner makes the
// "don't edit by hand" contract explicit.
//
// Output is stable for any given input: sprites and holidays land in
// the order they appear in the document so the user-visible diff after
// a drag corresponds to the moved sprite alone.
func emitMascotsTf(c mascot.Canvas, sprites []mascot.Sprite, holidays []mascot.Holiday) string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n")
	b.WriteString(`resource "magicmirror_mascot_layout" "default" {` + "\n")
	fmt.Fprintf(&b, "  canvas_width  = %d\n", positiveOrDefault(c.Width, mascot.DefaultWidth))
	fmt.Fprintf(&b, "  canvas_height = %d\n", positiveOrDefault(c.Height, mascot.DefaultHeight))

	if len(sprites) == 0 {
		b.WriteString("\n  # no sprites placed yet — drag one in from the /mascot editor.\n")
	}
	for _, s := range sprites {
		b.WriteString("\n  sprite {\n")
		fmt.Fprintf(&b, "    id     = %q\n", s.ID)
		fmt.Fprintf(&b, "    sprite = %q\n", s.Sprite)
		fmt.Fprintf(&b, "    x      = %d\n", s.X)
		fmt.Fprintf(&b, "    y      = %d\n", s.Y)
		fmt.Fprintf(&b, "    w      = %d\n", s.W)
		fmt.Fprintf(&b, "    h      = %d\n", s.H)
		b.WriteString("  }\n")
	}
	for _, h := range holidays {
		b.WriteString("\n  holiday {\n")
		fmt.Fprintf(&b, "    state = %q\n", h.State)
		fmt.Fprintf(&b, "    start = %q  # MM-DD\n", h.Start)
		fmt.Fprintf(&b, "    end   = %q\n", h.End)
		b.WriteString("  }\n")
	}
	b.WriteString("}\n")
	return b.String()
}

const banner = `# MMM-Mascot layout (HOM-117). Regenerated by magicmirror-agent's
# /mascot editor on each Save. Hand edits WILL be overwritten — make
# layout changes in the editor; if you need terraform-only fields the
# editor cannot express, declare them in modules.tf instead.
`

func positiveOrDefault(v, dflt int) int {
	if v <= 0 {
		return dflt
	}
	return v
}
