#!/bin/bash
# Magic Mirror Agent Installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/SkylerGodfrey/MMM-Terraform/main/scripts/install-agent.sh | bash
#
# With options (note the 'bash -s --' syntax):
#   curl -fsSL https://raw.githubusercontent.com/SkylerGodfrey/MMM-Terraform/main/scripts/install-agent.sh | bash -s -- --version 0.1.0
#   curl -fsSL https://raw.githubusercontent.com/SkylerGodfrey/MMM-Terraform/main/scripts/install-agent.sh | bash -s -- --no-service
#   curl -fsSL https://raw.githubusercontent.com/SkylerGodfrey/MMM-Terraform/main/scripts/install-agent.sh | bash -s -- --help

set -e

# Configuration
REPO="SkylerGodfrey/MMM-Terraform"
BINARY_NAME="magicmirror-agent"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/magicmirror-agent"
SERVICE_NAME="magicmirror-agent"

# Default options
VERSION="latest"
INSTALL_SERVICE=true
MM_CONFIG_PATH="/home/pi/MagicMirror/config/config.js"
MM_RESTART_CMD="pm2 restart MagicMirror"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --version)
            VERSION="$2"
            shift 2
            ;;
        --no-service)
            INSTALL_SERVICE=false
            shift
            ;;
        --mm-config)
            MM_CONFIG_PATH="$2"
            shift 2
            ;;
        --mm-restart-cmd)
            MM_RESTART_CMD="$2"
            shift 2
            ;;
        --help)
            echo "Magic Mirror Agent Installer"
            echo ""
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --version VERSION    Install specific version (default: latest)"
            echo "  --no-service         Don't install systemd service"
            echo "  --mm-config PATH     Path to Magic Mirror config.js"
            echo "  --mm-restart-cmd CMD Command to restart Magic Mirror"
            echo "  --help               Show this help message"
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            ;;
    esac
done

# Detect OS and architecture
detect_platform() {
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)

    case $ARCH in
        x86_64)  ARCH="amd64" ;;
        aarch64) ARCH="arm64" ;;
        armv7l)  ARCH="arm" ;;
        arm64)   ARCH="arm64" ;;
        *)       error "Unsupported architecture: $ARCH" ;;
    esac

    case $OS in
        linux)  ;;
        darwin) ;;
        *)      error "Unsupported OS: $OS" ;;
    esac

    PLATFORM="${OS}-${ARCH}"
    info "Detected platform: $PLATFORM"
}

# Get the download URL for the binary
get_download_url() {
    if [ "$VERSION" = "latest" ]; then
        info "Fetching latest release..."
        RELEASE_URL="https://api.github.com/repos/${REPO}/releases/latest"
        VERSION=$(curl -fsSL "$RELEASE_URL" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
        if [ -z "$VERSION" ]; then
            error "Could not determine latest version. Specify with --version"
        fi
        info "Latest version: $VERSION"
    fi

    DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${VERSION}/${BINARY_NAME}-${PLATFORM}"
    info "Download URL: $DOWNLOAD_URL"
}

# Download and install the binary
install_binary() {
    info "Downloading ${BINARY_NAME}..."

    TMP_FILE=$(mktemp)
    if ! curl -fsSL "$DOWNLOAD_URL" -o "$TMP_FILE"; then
        rm -f "$TMP_FILE"
        error "Failed to download binary. Check if the release exists: $DOWNLOAD_URL"
    fi

    info "Installing to ${INSTALL_DIR}/${BINARY_NAME}..."
    sudo mv "$TMP_FILE" "${INSTALL_DIR}/${BINARY_NAME}"
    sudo chmod +x "${INSTALL_DIR}/${BINARY_NAME}"

    info "Binary installed successfully"
}

# Create default configuration
create_config() {
    if [ -f "${CONFIG_DIR}/config.yaml" ]; then
        warn "Config file already exists at ${CONFIG_DIR}/config.yaml, skipping"
        return
    fi

    info "Creating configuration directory..."
    sudo mkdir -p "$CONFIG_DIR"

    info "Generating API key..."
    API_KEY=$(openssl rand -hex 32)

    info "Creating configuration file..."
    sudo tee "${CONFIG_DIR}/config.yaml" > /dev/null << EOF
# Magic Mirror Agent Configuration
# Generated by installer on $(date)

server:
  host: "0.0.0.0"
  port: 8484

magicmirror:
  config_path: "${MM_CONFIG_PATH}"
  restart_command: "${MM_RESTART_CMD}"

auth:
  enabled: true
  api_key: "${API_KEY}"
EOF

    sudo chmod 600 "${CONFIG_DIR}/config.yaml"

    echo ""
    info "Configuration created at ${CONFIG_DIR}/config.yaml"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Save your API key:${NC}"
    echo -e "${GREEN}${API_KEY}${NC}"
    echo ""
    echo "You'll need this key to configure the Terraform provider."
    echo ""
}

# Install systemd service
install_service() {
    if [ "$INSTALL_SERVICE" = false ]; then
        info "Skipping service installation (--no-service specified)"
        return
    fi

    if [ ! -d /etc/systemd/system ]; then
        warn "systemd not found, skipping service installation"
        return
    fi

    info "Installing systemd service..."

    sudo tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null << EOF
[Unit]
Description=Magic Mirror Terraform Agent
Documentation=https://github.com/${REPO}
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$(whoami)
Group=$(id -gn)

ExecStart=${INSTALL_DIR}/${BINARY_NAME} --config ${CONFIG_DIR}/config.yaml

Restart=on-failure
RestartSec=5

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=$(dirname "$MM_CONFIG_PATH")

StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable ${SERVICE_NAME}

    info "Service installed and enabled"
}

# Start the service
start_service() {
    if [ "$INSTALL_SERVICE" = false ]; then
        return
    fi

    if [ ! -d /etc/systemd/system ]; then
        return
    fi

    info "Starting ${SERVICE_NAME}..."
    sudo systemctl start ${SERVICE_NAME}

    sleep 2

    if systemctl is-active --quiet ${SERVICE_NAME}; then
        info "Service started successfully"
    else
        warn "Service may not have started correctly. Check: sudo journalctl -u ${SERVICE_NAME}"
    fi
}

# Verify installation
verify_installation() {
    echo ""
    info "Verifying installation..."

    if command -v ${BINARY_NAME} &> /dev/null; then
        info "Binary: OK ($(${BINARY_NAME} --version 2>/dev/null || echo 'installed'))"
    else
        warn "Binary not in PATH"
    fi

    if [ -f "${CONFIG_DIR}/config.yaml" ]; then
        info "Config: OK (${CONFIG_DIR}/config.yaml)"
    else
        warn "Config not found"
    fi

    if [ "$INSTALL_SERVICE" = true ] && [ -d /etc/systemd/system ]; then
        if systemctl is-active --quiet ${SERVICE_NAME}; then
            info "Service: OK (running)"
        else
            warn "Service: not running"
        fi
    fi

    # Test the API
    sleep 1
    if curl -sf http://localhost:8484/health > /dev/null 2>&1; then
        info "API: OK (responding on port 8484)"
    else
        warn "API: not responding (may still be starting)"
    fi

    echo ""
    info "Installation complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Note your API key (shown above)"
    echo "  2. Verify Magic Mirror config path in ${CONFIG_DIR}/config.yaml"
    echo "  3. Configure your Terraform provider with the API key"
    echo ""
    echo "Useful commands:"
    echo "  sudo systemctl status ${SERVICE_NAME}  # Check status"
    echo "  sudo journalctl -u ${SERVICE_NAME} -f  # View logs"
    echo "  curl http://localhost:8484/health      # Test API"
    echo ""
}

# Main installation flow
main() {
    echo ""
    echo "========================================="
    echo "  Magic Mirror Agent Installer"
    echo "========================================="
    echo ""

    # Check for root/sudo
    if [ "$EUID" -ne 0 ] && ! sudo -n true 2>/dev/null; then
        warn "This script requires sudo access for installation"
        sudo -v || error "Failed to obtain sudo access"
    fi

    detect_platform
    get_download_url
    install_binary
    create_config
    install_service
    start_service
    verify_installation
}

main
